config/routes.rb
Rails.application.routes.draw do
  

  resources :thanks
  devise_for :users
  root 'home#about'

  resources :posts do
    collection do
      get :tag
    end
  end

  match ':controller(/:action(/:id))', :via => [:get, :post]

  mathjax 'mathjax'

end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_taggable_on :tags
	fuzzily_searchable :title
end

app/models/thank.rb
class Thank < ActiveRecord::Base
end

app/models/trigram.rb
class Trigram < ActiveRecord::Base
  include Fuzzily::Model
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_length_of :email, :minimum => 5, :maximum => 250, :allow_blank => false
  validates_length_of :first_name, :minimum => 2, :maximum => 250, :allow_blank => false
  validates_length_of :last_name, :minimum => 2, :maximum => 250, :allow_blank => false
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:first_name, :last_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password << :admin)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'ExchangeRateVlad'
  ExchangeRate.init("http://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml")
  def index
  end
  def exchange
  	@currencies = ExchangeRate.get_currencies()
  	@times = ExchangeRate.get_times()
  end
  def convert
  	@currencies = ExchangeRate.get_currencies()
  	@times = ExchangeRate.get_times()

  	d = DateTime.parse(params[:home][:date])
    @r = [ExchangeRate.at(d, params[:home][:c1], params[:home][:c2]) * params[:home][:amount].to_f, 
    	params[:home][:c1], params[:home][:c2],params[:home][:amount], params[:home][:date]]
	p @r
   render :action => :exchange
  end
  def send_email
  	Emailer.raw_email('vladotrocol@gmail.com', params[:home][:subject], params[:home][:body]).deliver
  	redirect_to(:controller => '/home', :action => 'about')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
    if params[:search]
      results = Post.find_by_fuzzy_title(params[:search])
      tagged_results = Post.tagged_with("#{params[:search]}", :any => true)
      @posts = (Kaminari.paginate_array((results+tagged_results).uniq)).page(params[:page]).per(1)
    else  
       @posts = Post.page(params[:page]).per(1).order("created_at DESC")  
    end
    @users = User.all
    @recent = Post.all.order("created_at desc").limit(5)
  end

  def tag
    @posts = Post.tagged_with(params[:tag]).page(params[:page]).per(2).order("created_at DESC")
    @users = User.all
    @recent = Post.all.order("created_at desc").limit(5)
    render :action => 'index'
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @users = User.all
    @recent = Post.all.order("created_at desc").limit(5)
  end

  # GET /posts/new
  def new
    @post = Post.new
    @recent = Post.all.order("created_at desc").limit(5)
  end

  # GET /posts/1/edit
  def edit
    @recent = Post.all.order("created_at desc").limit(5)
  end

  # POST /posts
  # POST /posts.json

  def create
    if current_user.admin>0
      @post = Post.new(post_params)
      @post.author = current_user.id
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to posts_path, notice: "Only admins can post new articles."
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @recent = Post.all.order("created_at desc").limit(5)
    respond_to do |format|
      if current_user.admin>0
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
def delete
    @done = Post.find(params[:id])
    if current_user.admin>0
      if @done.destroy
        redirect_to posts_path, notice: "The article has been successfully deleted."
      else
        redirect_to posts_path, notice: "The article could not be deleted."
      end
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :content, :author, :tag_list)
    end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :set_thank, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /thanks
  # GET /thanks.json
  def index
    @thanks = Thank.page(params[:page]).per(5).order("created_at DESC")
  end

  # GET /thanks/1
  # GET /thanks/1.json
  def show
     @thanks = Thank.page(params[:page]).per(5).order("created_at DESC")
  end

  # GET /thanks/new
  def new
     @thanks = Thank.where(author: current_user.id).page(params[:page]).per(5).order("created_at DESC")
    @thank = Thank.new
  end

  # GET /thanks/1/edit
  def edit
  end

  # POST /thanks
  # POST /thanks.json
  def create
    @thank = Thank.new(thank_params)
    @thank.author = current_user.id

      if @thank.save
        redirect_to new_thank_path, notice: 'Thank was successfully created.' 
      else
        redirect_to new_thank_path, notice: 'Thank was not successfully created.' 
      end

  end

  # PATCH/PUT /thanks/1
  # PATCH/PUT /thanks/1.json
  def update
    respond_to do |format|
      if @thank.update(thank_params)
        format.html { redirect_to @thank, notice: 'Thank was successfully updated.' }
        format.json { render :show, status: :ok, location: @thank }
      else
        format.html { render :edit }
        format.json { render json: @thank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thanks/1
  # DELETE /thanks/1.json
  def delete
    @done = Thank.find(params[:id])
    if @done.destroy
       redirect_to new_thank_path, notice: 'Thank was successfully deleted.' 
    else
        redirect_to new_thank_path, notice: 'Thank was not successfully deleted.' 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thank
      @thank = Thank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thank_params
      params.require(:thank).permit(:content, :author)
    end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  def index
  end

  def running_time
  end

  def linked_lists
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/home/about.html.erb
<div class='col-md-8 col-md-offset-2 text-center'>

  <div class = 'moto container centered text-center'>
    <div class='profile-pic centered text-center'>
      <%=image_tag("n.jpg", class: "profile-rounded", size: "160x160")%>
        </br>
      <h3> Vlad Stefan Otrocol</h3> <h5>Suceava, Romania </h5>
    </div>

    <div class='profile-text text-justify'>
      
        <i class='text-justify'>I am a science and technology enthusiast. I work with a large range of technologies on exciting projects. My background is in computer science with an engineering masters degree from University of Bristol. My main fields of focus are Human-Computer Interaction, Computer Vision and Cryptography. I also have a keen interest in the issue of big ideas in areas such as philosophy, education, macro-economics, politics and psychology. My latest hobby is quantum programming. </i>
    </div>
      <hr>
  </div>


    <div class='skills container text-center centered'>
      <div class='col-md-4 hire'>
        <div class='col-md-10 '>
          <div class='centered text-center fw'>
            </br>Currently seeking jobs?</br><span class='red'><h5><b>YES</b></h5></span>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#sendMail">Contact me
            </button>
          </div>
          <div class="modal fade" id="sendMail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h3 class="modal-title" id="myModalLabel">Send Email</h3>
                </div>
                <div class="modal-body text-left">
                  
                  
                  <%= form_for(:home, :url => {:action => 'send_email'}) do |f| %>
                  
                  <div class="form-group">
                    <%= f.label :subject, class: 'control-label' %><br>
                    <%= f.text_field(:subject, class: 'form-control')%>
                  </div>
                  <div class="form-group">
                    <%= f.label :body, class: 'control-label' %><br>
                    <%= f.text_area(:body, rows: 10, class: 'form-control')%>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <%= submit_tag "Send", class: "btn btn-primary" %>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class='col-md-4 text-left'>
        <h5><b>Programming:</b></h5>
        <table id='programming-skills'>
          <tr>
            <td>C++</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>Java</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>Ruby</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>Python</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>C#</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
        </table>
      </div>
      <div class='col-md-4 text-left'>
        <h5><b>Languages:</b></h5>
        <table  id='languages-skills'>
          <tr>
            <td>English</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>Romanian</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>German</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>Japanese</td>
            <td><i class="fa fa-circle"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
          <tr>
            <td>Moldavian*</td>
            <td><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i><i class="fa fa-circle-o"></i></td>
          </tr>
        </table>
      </div>
    </div>

  <div class='link-container container'> 
    <hr>
    <%= link_to 'https://www.facebook.com/vlad.otrocol' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-facebook-official"></i></div>
    <div class='about-link hvr-fade'>&nbsp&nbspFacebook</div></div>
    <% end %>
    <%= link_to 'https://uk.linkedin.com/in/vladotrocol' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-linkedin-square"></i></div>
    <div class='about-link hvr-fade'>&nbsp&nbspLinkedin</div></div>
    <% end %>
    <%= link_to 'https://twitter.com/otrocolvlad' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-twitter-square"></i></div> 
    <div class='about-link hvr-fade'>&nbsp&nbspTwitter</div></div>
    <% end %>
    <%= link_to 'http://stackoverflow.com/users/1114100/vlad-otrocol' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-stack-overflow"></i></div> 
    <div class='about-link hvr-fade'>&nbsp&nbspStackoverflow</div></div>
    <% end %>
    <%= link_to 'https://github.com/vladotrocol' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-github-square"></i></div>
    <div class='about-link hvr-fade'>&nbsp&nbspGithub</div></div>
    <% end %>
    <%= link_to 'https://bitbucket.org/vladotrocol' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-bitbucket-square"></i></div>
    <div class='about-link hvr-fade'>&nbsp&nbspBitbucket</div></div>
    <% end %>
    <%= link_to 'http://dl.acm.org/author_page.cfm?id=87958797557&coll=DL&dl=ACM&trk=0&cfid=493813538&cftoken=65871069' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-graduation-cap"></i></div>
    <div class='about-link hvr-fade'>&nbsp&nbspACM</div></div>
    <% end %> 
    <%= link_to 'http://lizozomro.deviantart.com/gallery/' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-deviantart"></i></div> 
    <div class='about-link hvr-fade'>&nbsp&nbspDevianart</div></div>
    <% end %>
    <%= link_to 'https://www.youtube.com/user/lizozomro2/videos' do %>
    <div class='about-link-icon'><div class='link-icon'><i class="fa fa-youtube-square"></i></div>
    <div class='about-link hvr-fade'>&nbsp&nbspYoutube</div></div>
    <% end %>
  </div>

app/views/home/exchange.html.erb
<br>
<div class='col-md-6 col-md-offset-3 text-center article_post'>
	<h1 class = 'text-center'>Exchange</h1>
	<hr>
	 <%= form_for(:home, :url => {:action => 'convert'}, :html => {:"data-parsley-validate" => ''}) do |f| %>
	 <div class='row'>
		        <div class='col-sm-6'>
		        	<div class="form-group">
		            	<%= f.label 'From:', class: 'control-label'%>              
						<%= f.select :c1, @currencies, {:selected => 'EUR'}, {:class => 'form-control', :"required" => '',
							:"data-parsley-trigger" => "change"}%>
		            </div>

					<div class="form-group">
		            	<%= f.label 'Time:', class: 'control-label'%>
		                <div class='input-group date datetimepicker'>               
							<%= f.text_field :date, :class => 'form-control my_date_field', :value =>  Date.today.strftime("%Y-%m-%d"), :"required" => '',:"data-parsley-trigger" => "change", :"data-parsley-errors-messages-disabled" =>''%>
		                    <span class="input-group-addon">
		                        <span class="glyphicon glyphicon-calendar"></span>
		                    </span>
		                </div>
		            </div>		        	
		        </div>
		       	<div class='col-sm-6'>
		            <div class='form-group'>
		            	<%= f.label "To:", class: 'control-label'%>
		            	<%= f.select :c2,@currencies, {:selected => 'RON'}, {:class => 'form-control', :"required" => '',:"data-parsley-trigger" => "change"}%>
		        	</div>
		            <div class='form-group'>
		            	<%= f.label "Amount:", class: 'control-label'%>
		            	<%= f.number_field :amount, :value => 1, class: 'form-control', :"required" => '',:"data-parsley-trigger" => "change", :"data-parsley-type" => "number", :step => 'any'%>
		        	</div>
		        </div>
		    </div>
		        <hr>
	 	<%= submit_tag "Convert", class: "btn btn-danger" %>
	 	<hr>
	 <%end%>
	 <%if @r%>
	 	<h5 class='text-center'>Rate at: <%=@r[4]%></h5>
	 	<div class='row modal-body' >
	 		<div class='col-sm-5 alert alert-info'>
	 			<%=@r[3] + "   " + @r[1]%>
	 		</div>
	 		<div class='col-sm-2'>
				<span class="glyphicon glyphicon-resize-horizontal" style='font-size:3em;'></span>
	 		</div>
	 		<div class='col-sm-5 alert alert-success'>
	 			<%=@r[0].to_s + "   " + @r[2]%>
	 		</div>

	 	</div>
	 <%end%>
</div>
			
<%= javascript_tag do %>
  	goodDates = <%= @times.to_json.html_safe %>;
<% end %>

<script type="text/javascript">
	$(document).on('ready page:load page:change page:restore',  function() {
		var defaultD = goodDates[0];
		$('.my_date_field').attr('value', defaultD);
		$('.datetimepicker').datetimepicker({
			format: "YYYY-MM-DD",
			enabledDates: goodDates
		});
	});
</script>

app/views/home/resume.html.erb
<div class='pdfV' id='CV'>
<object data='/vladotrocolCV.pdf#' 
        type='application/pdf' 
        width='100%' 
        height='100%'>

<p>It appears your Web browser is not configured to display PDF files. 
No worries, just <a href='/vladotrocolCV.pdf#'>click here to download the PDF file.</a></p>

</object></div>

app/views/layouts/_sidepanel.html.erb
<div class="sidepanel text-center wordwrap">
    <br>
    <% if user_signed_in? %>
    <% if current_user.admin>0%>
    <%= link_to "New Article", new_post_path, class: 'brand' %>
    <%else%>
    <br>
    <%end%>
    <%end%>
<%= form_tag(posts_path, :method => 'get') do %>
  <p>
    <div class = 'modal-body'><%= text_field_tag :search, params[:search], :placeholder => 'Search Article',class: 'form-control' %></div>
    
  </p>
<% end %>
    <h4>Most recent posts:</h4>
    <div class='panels_item panel_body'>
        <% @recent.each do |r| %>

            <small><%= link_to r.title, {:controller => 'posts', :action =>'show', :id => r.id} %> </small>
            <% if r != @recent.last %>
                <br />
            <% end %>
        <%end%>
    </div>
    <h4>Tags:</h4>
    <div id="tag_cloud", class="text-center modal-body wordwrap">
        <% tag_cloud Post.tag_counts.order('count desc').limit(26), %w{s m l} do |tag, css_class| %>
            <%= link_to (tag.name+'  ' + '<sup>' + tag.count.to_s + '</sup>').html_safe, { :action => :tag, :tag => tag.name }, class: (css_class + ' '+'label label-info')%>
        <% end %>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :description, class: 'control-label' %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, class: 'control-label' %>
    <%= f.text_area :content, rows: 40, id: 'froalaed' %>
  </div>
    <div class="form-group">
    <%= f.label :tag_list, "Tags (separated by spaces)", class: 'control-label' %><br />
  <%= f.text_field :tag_list, class: 'form-control'%>
</div>
  <div class="actions">

    <%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class='scroll'>
  <div class="post_wrap">
    <div class='col-md-10 col-md-offset-1'>
      <h1 style='color:#22aaaa;'><span class="glyphicon glyphicon-pencil-large" aria-hidden="true"></span> Edit</h1>        
<%= render "form" %>
    </div>
  </div>
  <%= render 'layouts/sidepanel'%>
</div>

app/views/posts/index.html.erb
<div class='scroll'>
    <div class="post_wrap">
        <div class='col-md-10 col-md-offset-1'>
            <h1 style='color:#22aaaa;' class='text-center'>Articles</h1>
            </br>
            <% @posts.each do |post| %>
            <div class=' article_post'>
                <div class='modal-body wordwrap'>

                    <h3 class='text-left'><%= link_to post.title, {:controller => 'posts', :action =>'show', :id => post.id} %>  </h3>

                    <!-- <p><small><em><%=post.description%></em></small>  </p> -->

                    <p class="text-muted"><small>Posted on: <%=post.created_at.strftime("%B #{post.created_at.day.ordinalize}, %Y")%>| by <%= @users.find(post.author).first_name%>
                        <%= @users.find(post.author).last_name%>
                    </small><p>
<hr>
                    <p><%= post.content.html_safe %></p>
                    <% if user_signed_in? %>
                    <% if current_user.admin>0%>
                    <hr><p class='f_right'>
                    <%= link_to "Show", {:controller => 'posts', :action =>'show', :id => post.id} %> |
                    <%= link_to "Edit", edit_post_path(post) %> |
                    <%= link_to "Delete", {:controller => '/posts', :action => "delete", :id => post.id} %></p>
                    <%end%>
                    <%end%>
                    <p>Tags: <%= raw post.tag_list.map { |t| link_to t, { :action => :tag, :tag => t }, {class: 'label label-info'}}.join(' ') %></p>
                </div>
            </div>
            <br /> 
            <% end %>
            <div class="text-center"><%= paginate @posts, :theme => 'twitter-bootstrap-3' %></div>
        </div>
    </div>
    <%= render 'layouts/sidepanel'%>
</div>

app/views/posts/new.html.erb
<div class="scroll">
        <div class='post_wrap'>
            <div class="col-md-10 col-md-offset-1">    
                <h3> New Article</h3>
                <%= render "form" %>
            </div>
        </div>
    <%= render 'layouts/sidepanel'%>
</div>    

app/views/posts/show.html.erb
<div class='scroll'>
	<div class='post_wrap'>
		<br>
		<div class = 'col-md-10 col-md-offset-1 article_post'>
			<h3 class='text-center'><%= link_to @post.title, {:controller => 'posts', :action =>'show', :id => @post.id} %></strong></h3>
			<p><em><%= @post.description %></em></p>
			 <p class="text-muted text-left"><small>Posted on: <%=@post.created_at.strftime("%B #{@post.created_at.day.ordinalize}, %Y")%>| by <%= @users.find(@post.author).first_name%>
                        <%= @users.find(@post.author).last_name%>
                    </small></p>
			
			
			 <hr>
			<p><%= @post.content.html_safe() %></p>
			<% if user_signed_in? %>
                    <% if current_user.admin>0%>
                    <hr><p class='f_right'>
                    <%= link_to "Show", {:controller => 'posts', :action =>'show', :id => @post.id} %> |
                    <%= link_to "Edit", edit_post_path(@post) %> |
                    <%= link_to "Delete", {:controller => '/posts', :action => "delete", :id => @post.id} %></p>
                    <%end%>
                    <%end%>
                    <p>Tags: <%= raw @post.tag_list.map { |t| link_to t, { :action => :tag, :tag => t }, {class: 'label label-info'}}.join(' ') %></p>
		</div>
	</div>
	<%=render 'layouts/sidepanel'%>
</div>

app/views/thanks/edit.html.erb
<h1>Editing Thank</h1>

<%= render 'form' %>

<%= link_to 'Show', @thank %> |
<%= link_to 'Back', thanks_path %>

app/views/thanks/index.html.erb
<div class='scroll'>
    <div class="post_wrap">
        <div class='col-md-10 col-md-offset-1'>
            <h1 style='color:#22aaaa;' class='text-center'>Today I am thankful for:</h1>
            </br>
            <% @thanks.each do |thank| %>
            <div class=' article_post'>
                <div class='modal-body wordwrap'>

                   
                    <p><%= thank.content.html_safe %> | 
 <span class="text-muted"><small>Posted on: <%=thank.created_at.strftime("%B #{thank.created_at.day.ordinalize}, %Y")%>
                    </small></span>
                    </p>
                    <% if user_signed_in? %>
                    <% if current_user.admin>0%>
                    <hr><p class='f_right'>
                    <%= link_to "Show", {:controller => '/thank', :action =>'show', :id => thank.id} %> |
                    <%= link_to "Edit", edit_thank_path(thank) %> |
                    <%= link_to "Delete", {:controller => '/thank', :action => "delete", :id => thank.id} %></p>
                    <%end%>
                    <%end%>
                </div>
            </div>
            <br /> 
            <% end %>
            <div class="text-center"><%= paginate @thanks, :theme => 'twitter-bootstrap-3' %></div>
        </div>
    </div>
    <%= render 'sidepanel'%>
</div>

app/views/thanks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_thank_path(@thank) %> |
<%= link_to 'Back', thanks_path %>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>